// Generated by CoffeeScript 1.6.3
$(function() {
  var $, $ajaxContainer, $body, $latestPost, $postIndex, History, NProgress, loadPromise, loading, showIndex;
  $ = window.$, History = window.History, NProgress = window.NProgress;
  $body = $(document.body);
  $ajaxContainer = $("#ajax-container");
  $latestPost = $("#latest-post");
  $postIndex = $("#post-index");
  loading = false;
  showIndex = false;
  loadPromise = null;
  $latestPost.show();
  $postIndex.hide();
  if (window.location.pathname.indexOf("page") === 1) {
    $latestPost.hide();
    $postIndex.show();
  }
  if (!History.enabled) {
    false;
  }
  History.Adapter.bind(window, "statechange", function() {
    var state;
    state = History.getState();
    return $.ajax({
      url: state.url,
      type: "get"
    }).then(function(result) {
      var $html, $newContent;
      $html = $(result);
      $newContent = $html.find("#ajax-container").contents();
      $body.animate({
        scrollTop: 0
      });
      return $ajaxContainer.fadeOut(500, function() {
        $latestPost = $newContent.find("#latest-post");
        $postIndex = $newContent.find("#post-index");
        if (showIndex) {
          $latestPost.hide();
        } else {
          $latestPost.show();
          $postIndex.hide();
        }
        $ajaxContainer.html($newContent);
        $ajaxContainer.fadeIn(500);
        NProgress.done();
        loading = false;
        return showIndex = false;
      });
    }, function() {
      NProgress.done();
      loading = false;
      return showIndex = false;
    });
  });
  return $body.on("click", ".js-ajax-link, .pagination a", function(e) {
    var $this, currentState, title, url;
    e.preventDefault();
    if (loading) {
      return;
    }
    $this = $(this);
    currentState = History.getState();
    url = $this.attr("href");
    title = $this.attr("title");
    if (url !== currentState.url) {
      loading = true;
      if ($this.hasClass("js-show-index") || $this.parent(".pagination").length) {
        showIndex = true;
      }
      NProgress.start();
      return History.pushState({
        salt: new Date().getTime()
      }, title, url);
    } else {
      $body.animate({
        scrollTop: 0
      });
      NProgress.start();
      if ($this.hasClass("js-show-index")) {
        return $latestPost.fadeOut(300, function() {
          $postIndex.fadeIn(300);
          return NProgress.done();
        });
      } else {
        return $postIndex.fadeOut(300, function() {
          $latestPost.fadeIn(300);
          return NProgress.done();
        });
      }
    }
  });
});
